server:
  port: 8761

eureka:
#  instance:
#    hostname: service-registry
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      default-zone: http://${eureka.instance.hostname}:8761/eureka